### ISSUE TITLE
Contexts - App Context Integration Tests

### ISSUE THREAD

**Issue by Ashatz** [greatstrength/tiferet#167]
# Solution Overview

This document outlines the implementation of a user story to add integration tests for the Tiferet framework’s application context by creating test commands, test cases, and a configuration file for a basic calculator application. The changes introduce a new package for test commands, a test module for verifying calculator operations, and a YAML configuration to define the application’s behavior, aligning with Tiferet’s Domain-Driven Design principles and Kabbalistic philosophy of beauty in balance.

## User Story

As a Tiferet developer, I want to add integration tests in `tiferet/tests_int/__init__.py`, `tiferet/tests_int/test_main.py`, and `tiferet/configs/tests/test_calc.yml` to validate the application context’s ability to execute calculator features, so that the framework’s functionality is verified, ensuring clarity, reliability, and extensibility.

#### Integration Test Updates

- Create `tiferet/tests_int/__init__.py` with:
  - Imports:
    - Import `Command` from `tiferet.commands`.
  - Classes:
    - `TestAddNumber`: Command to add two numbers, returning their sum as an integer.
    - `TestSubtractNumber`: Command to subtract two numbers, returning their difference as an integer.
    - `TestMultiplyNumber`: Command to multiply two numbers, returning their product as an integer.
    - `TestDivideNumber`: Command to divide two numbers, returning their quotient as a float, with error handling for division by zero.
- Create `tiferet/tests_int/test_main.py` with:
  - Imports:
    - Import `pytest` for testing and `App` from `tiferet`.
  - Fixtures:
    - `app_context`: Initializes an `App` instance with settings for `AppYamlProxy` and the test configuration file.
    - `basic_calc`: Loads the `test_calc` interface from the app context.
  - Tests:
    - `test_basic_calc_add_numbers`: Verifies addition (5 + 3 = 8).
    - `test_basic_calc_subtract_numbers`: Verifies subtraction (5 - 3 = 2).
    - `test_basic_calc_multiply_numbers`: Verifies multiplication (5 * 3 = 15).
    - `test_basic_calc_divide_numbers`: Verifies division (6 / 3 = 2).
    - `test_basic_calc_divide_by_zero`: Verifies division by zero error handling.
    - `test_basic_calc_square_number`: Verifies squaring (4 * 4 = 16).
- Create `tiferet/configs/tests/test_calc.yml` with:
  - Attributes: Map arithmetic commands to their classes in `tiferet.tests_int`.
  - Errors: Define `DIVISION_BY_ZERO` with a localized message.
  - Features: Define addition, subtraction, multiplication, division, and squaring features, with squaring reusing the multiplication command.
  - Interfaces: Define `test_calc` with dependencies (repositories, services, contexts) and configuration file paths.

#### General Criteria

- Preserve all provided code’s comments, docstrings, and spacing exactly.
- Ensure compatibility with `App`, `AppContext`, `FeatureContext`, `ErrorContext`, `ContainerContext`, `AppYamlProxy`, `FeatureYamlProxy`, `ErrorYamlProxy`, `FeatureHandler`, `ContainerHandler`, `ErrorHandler`, and `Command`.
- No additional modules or updates to other `__init__.py` files unless specified.

### Add Integration Test Commands

- **File**: `tiferet/tests_int/__init__.py`
- **Description**: Creates a new package with commands for arithmetic operations to support integration testing.
- **Placement**: Create the file with the provided content, including `# -- new` comments for all artifacts. **Developers must remove all `# -- new` comments after transferring the file content to the codebase to ensure clean code.**
- **Code**:
  ```python
  # *** imports

  # -- new
  # ** app
  from ..commands import *

  # *** classes

  # -- new
  # ** class: TestAddNumber
  class TestAddNumber(Command):
      '''
      A command to add two numbers.
      '''

      # -- new
      # * method: execute
      def execute(self, a: int, b: int, **kwargs) -> int:
          '''
          Execute the command to add two numbers.

          :param a: The first number.
          :type a: int
          :param b: The second number.
          :type b: int
          :param kwargs: Additional keyword arguments.
          :type kwargs: dict
          :return: The sum of the two numbers.
          :rtype: int
          '''
          
          # Return the sum of the two numbers.
          return int(a) + int(b)
      

  # -- new
  # ** class: TestSubtractNumber
  class TestSubtractNumber(Command):
      '''
      A command to subtract two numbers.
      '''

      # -- new
      # * method: execute
      def execute(self, a: int, b: int, **kwargs) -> int:
          '''
          Execute the command to subtract two numbers.

          :param a: The first number.
          :type a: int
          :param b: The second number.
          :type b: int
          :param kwargs: Additional keyword arguments.
          :type kwargs: dict
          :return: The difference of the two numbers.
          :rtype: int
          '''
          
          # Return the difference of the two numbers.
          return int(a) - int(b)
      

  # -- new
  # ** class: TestMultiplyNumber
  class TestMultiplyNumber(Command):
      '''
      A command to multiply two numbers.
      '''

      # -- new
      # * method: execute
      def execute(self, a: int, b: int, **kwargs) -> int:
          '''
          Execute the command to multiply two numbers.

          :param a: The first number.
          :type a: int
          :param b: The second number.
          :type b: int
          :param kwargs: Additional keyword arguments.
          :type kwargs: dict
          :return: The product of the two numbers.
          :rtype: int
          '''
          
          # Return the product of the two numbers.
          return int(a) * int(b)
      

  # -- new
  # ** class: TestDivideNumber
  class TestDivideNumber(Command):
      '''
      A command to divide two numbers.
      '''

      # -- new
      # * method: execute
      def execute(self, a: int, b: int, **kwargs) -> float:
          '''
          Execute the command to divide two numbers.

          :param a: The numerator.
          :type a: int
          :param b: The denominator.
          :type b: int
          :param kwargs: Additional keyword arguments.
          :type kwargs: dict
          :return: The quotient of the two numbers.
          :rtype: float
          '''
          
          # Raise an error if the denominator is zero.
          if int(b) == 0:
              self.raise_error(
                  'DIVISION_BY_ZERO',
                  'Cannot divide by zero.',
              )

          # Return the quotient of the two numbers.
          return int(a) / int(b)
  ```

### Add Integration Test Cases

- **File**: `tiferet/tests_int/test_main.py`
- **Description**: Creates a test module with pytest fixtures and test cases to validate calculator operations.
- **Placement**: Create the file with the provided content, including `# -- new` comments for all artifacts. **Developers must remove all `# -- new` comments after transferring the file content to the codebase to ensure clean code.**
- **Code**:
  ```python
  # *** imports

  # -- new
  # ** infra
  import pytest

  # -- new
  # ** app
  from .. import App


  # *** fixtures

  # -- new
  # ** fixture: app_context
  @pytest.fixture
  def app_context():

      return App(settings=dict(
          app_repo_module_path='tiferet.proxies.yaml.app',
          app_repo_class_name='AppYamlProxy',
          app_repo_params=dict(
              app_config_file='tiferet/configs/tests/test_calc.yml'
          )
      ))


  # -- new
  # ** fixture: basic_calc
  @pytest.fixture
  def basic_calc(app_context):
      """
      Fixture to load the basic calculator interface from the app context.
      """

      # Load the basic_calc interface using the app context.
      return app_context.load_interface('test_calc')


  # *** tests

  # -- new
  # ** test: basic_calc_add_numbers
  def test_basic_calc_add_numbers(basic_calc):
      """
      Test the addition operation of the basic calculator.
      """

      # Perform addition using the basic_calc interface.
      result = basic_calc.run(
          'test_calc.add_number',
          data=dict(
              a=5,
              b=3
          )
      )

      # Assert that the result is as expected.
      assert result == 8, f"Expected 8, got {result}"


  # -- new
  # ** test: basic_calc_subtract_numbers
  def test_basic_calc_subtract_numbers(basic_calc):   
      """
      Test the subtraction operation of the basic calculator.
      """

      # Perform subtraction using the basic_calc interface.
      result = basic_calc.run(
          'test_calc.subtract_number',
          data=dict(
              a=5,
              b=3
          )
      )

      # Assert that the result is as expected.
      assert result == 2, f"Expected 2, got {result}"


  # -- new
  # ** test: basic_calc_multiply_numbers
  def test_basic_calc_multiply_numbers(basic_calc):
      """
      Test the multiplication operation of the basic calculator.
      """

      # Perform multiplication using the basic_calc interface.
      result = basic_calc.run(
          'test_calc.multiply_number',
          data=dict(
              a=5,
              b=3
          )
      )

      # Assert that the result is as expected.
      assert result == 15, f"Expected 15, got {result}"


  # -- new
  # ** test: basic_calc_divide_numbers
  def test_basic_calc_divide_numbers(basic_calc):
      """
      Test the division operation of the basic calculator.
      """

      # Perform division using the basic_calc interface.
      result = basic_calc.run(
          'test_calc.divide_number',
          data=dict(
              a=6,
              b=3
          )
      )

      # Assert that the result is as expected.
      assert result == 2, f"Expected 2, got {result}"


  # -- new
  # ** test: basic_calc_divide_by_zero
  def test_basic_calc_divide_by_zero(basic_calc):
      """
      Test the division by zero operation of the basic calculator.
      """

      # Perform division by zero using the basic_calc interface.
      
      result = basic_calc.run(
          'test_calc.divide_number',
          data=dict(
              a=6,
              b=0
          )
      )

      assert result.get('error_code') == 'DIVISION_BY_ZERO'
      assert result.get('message') == 'Division by zero is not allowed.'


  # -- new
  # ** test: basic_calc_square_number
  def test_basic_calc_square_number(basic_calc):
      """
      Test the squaring operation of the basic calculator.
      """

      # Perform squaring using the basic_calc interface.
      result = basic_calc.run(
          'test_calc.square_number',
          data=dict(
              a=4
          )
      )

      # Assert that the result is as expected.
      assert result == 16, f"Expected 16, got {result}"
  ```

### Add Test Configuration

- **File**: `tiferet/configs/tests/test_calc.yml`
- **Description**: Creates a YAML configuration file to define attributes, errors, features, and interfaces for the calculator application.
- **Placement**: Create the file with the provided content, including `# -- new` comments for all artifacts. **Developers must remove all `# -- new` comments after transferring the file content to the codebase to ensure clean code.**
- **Code**:
  ```yaml
  # -- new
  attrs:
    # -- new
    add_number_cmd:
      class_name: TestAddNumber
      module_path: tiferet.tests_int
    # -- new
    subtract_number_cmd:
      class_name: TestSubtractNumber
      module_path: tiferet.tests_int
    # -- new
    multiply_number_cmd:
      class_name: TestMultiplyNumber
      module_path: tiferet.tests_int
    # -- new
    divide_number_cmd:
      class_name: TestDivideNumber
      module_path: tiferet.tests_int
  # -- new
  errors:
    # -- new
    divide_by_zero:
      name: Division by Zero
      description: This error occurs when an attempt is made to divide by zero.
      error_code: DIVISION_BY_ZERO
      message:
      - lang: en_US
        text: Division by zero is not allowed.
  # -- new
  features:
    # -- new
    test_calc.add_number:
      commands:
      - attribute_id: add_number_cmd
        name: Add Number Command
      description: Adds two numbers.
      name: Add Number Feature
    # -- new
    test_calc.subtract_number:
      commands:
      - attribute_id: subtract_number_cmd
        name: Subtract Number Command
      description: Subtracts two numbers.
      name: Subtract Number Feature
    # -- new
    test_calc.multiply_number:
      commands:
      - attribute_id: multiply_number_cmd
        name: Multiply Number Command
      description: Multiplies two numbers.
      name: Multiply Number Feature
    # -- new
    test_calc.divide_number:
      commands:
      - attribute_id: divide_number_cmd
        name: Divide Number Command
      description: Divides two numbers.
      name: Divide Number Feature
    # -- new
    test_calc.square_number:
      commands:
      - attribute_id: multiply_number_cmd
        name: Square Number Command
        params:
          b: $r.a
      description: Squares a number.
      name: Square Number Feature
  # -- new
  interfaces:
    # -- new
    test_calc:
      attrs:
        container_repo:
          class_name: ContainerYamlProxy
          module_path: tiferet.proxies.yaml.container
        feature_repo:
          class_name: FeatureYamlProxy
          module_path: tiferet.proxies.yaml.feature
        error_repo:
          class_name: ErrorYamlProxy
          module_path: tiferet.proxies.yaml.error
        feature_service:
          class_name: FeatureHandler
          module_path: tiferet.handlers.feature
        container_service:
          class_name: ContainerHandler
          module_path: tiferet.handlers.container
        error_service:
          class_name: ErrorHandler
          module_path: tiferet.handlers.error
        container:
          class_name: ContainerContext
          module_path: tiferet.contexts.container
        features:
          class_name: FeatureContext
          module_path: tiferet.contexts.feature
        errors:
          class_name: ErrorContext
          module_path: tiferet.contexts.error
      const:
        container_config_file: tiferet/configs/tests/test_calc.yml
        feature_config_file: tiferet/configs/tests/test_calc.yml
        error_config_file: tiferet/configs/tests/test_calc.yml
      description: The interface instance for testing the calculator features.
      name: Integration Test - Basic Int Calculator
  ```

#### Notes
- The `TestDivideNumber` command uses `self.raise_error`, assumed to be inherited from `Command` or available in `tiferet.commands`.
- The `test_basic_calc_divide_by_zero` test expects a dictionary response with `error_code` and `message`, implying `ErrorContext.handle_error` returns such a structure.
- Assumed dependencies: `Command` in `tiferet/commands/__init__.py`, `App` in `tiferet/__init__.py`, `AppYamlProxy`, `FeatureYamlProxy`, `ErrorYamlProxy` in `tiferet/proxies/yaml/*`, `FeatureHandler`, `ContainerHandler`, `ErrorHandler` in `tiferet/handlers/*`, and `ContainerContext`, `FeatureContext`, `ErrorContext` in `tiferet/contexts/*`.
- The configuration file assumes `tiferet.proxies.yaml` modules exist for repository proxies.
